[package]
name = "identity-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = "1.0.136"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
dotenv = "0.15.0"
uuid = { version = "1", features = ["serde", "v4"] }